project:
  type: website
  output-dir: docs
  
website:
  title: "INLA workshop 2025"
  page-footer:
    left: "&copy; Copyright 2025, DCC"

format:
  html:
    page-layout: full
    theme: flatly # cosmo, flatly, yeti, sandstone
    # fontcolor: black
    smooth-scroll: true
    toc: false
    link-external-icon: true
    link-external-newwindow: true

editor: source

