project:
  type: website
  output-dir: docs
  
website:
  title: "INLA workshop 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, DCC"

format:
  html:
    theme: cerulean
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: source

