project:
  type: website
  output-dir: docs
  
website:
  title: "INLA workshop 2025"
  navbar:
    left:
      - href: index.qmd
        text: Homes
      - registration.qmd
      - keynotes.qmd
      - invited.qmd
      - abstract.qmd
      - contact.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, DCC"

format:
  html:
    page-layout: article
    theme: cosmo
    fontcolor: black
    smooth-scroll: true
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: source

